---

- name: "Run test '{{ tox_envlist }}' test cases from '{{ tox_dir }}'"
  shell:
    chdir: "{{ tox_dir }}"
    cmd: |
        {{ tox_command }} -e '{{ tox_envlist }}' {{ tox_extra_args }} -- \
            {{ tox_posargs }}
        exit_status=$?
        {{ tox_command }} -c '{{ tobiko_dir }}' -e report
        exit "${exit_status}"
  environment:
    TOBIKO_TEST_REPORT_DIR: "{{ test_report_dir }}"
    TOBIKO_TEST_REPORT_NAME: "{{ test_report_prefix }}{{ test_report_name }}"
