---

- become: yes
  become_user: "{{ tobiko_user }}"
  environment:
    PYTHON_VERSION: "{{ python_version }}"
  block:

    - when: tobiko_pre_run | bool
      block:
        - include: pre-run/source.yaml
        - include: pre-run/config.yaml
        - include: pre-run/output.yaml
        - include: pre-run/tools.yaml

    - when: tobiko_run | bool
      block:
        - include: run/tests.yaml
          when: tobiko_run_tests | bool

        - include: run/faults.yaml
          when: tobiko_run_faults | bool

    - when: tobiko_post_run | bool
      block:
        - include: post-run/report.yaml
