---
- name: Install Tobiko
  hosts: undercloud
  any_errors_fatal: true
  gather_facts: yes

  tasks:
      - name: Install required packages
        become: yes
        yum:
            name: "{{ item }}"
            state: present
        with_items:
            - 'python-virtualenv'
            - 'git'

      - name: Clone Tobiko project
        git:
            repo: 'https://github.com/rhos-infra/tobiko'
            dest: "~/tobiko"

      - name: Create Virtualenv
        pip:
            virtualenv: "~/tobiko_venv"
            name: "{{ item }}"
            state: latest
        with_items:
            - pip
            - setuptools
            - pbr

      - name: Install Tobiko
        pip:   
            chdir: "~/tobiko"
            virtualenv: "~/tobiko_venv"
            name: "." 
            editable: true
