- project:
    name: x/tobiko
    templates:
      - check-requirements
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - openstack-python37-jobs
      - release-notes-jobs-python3
      - publish-to-pypi
    check:
      jobs:
        - openstack-tox-pylint
        - openstack-tox-cover
        - tobiko-devstack-functional
        - tobiko-devstack-neutron-centos-7
        - tobiko-devstack-neutron-centos-7-queens
        - tobiko-devstack-neutron-centos-7-rocky
        - tobiko-devstack-neutron-centos-7-stein
        - tobiko-devstack-neutron-fedora-28
        - tobiko-devstack-neutron-ubuntu-bionic
    gate:
      jobs:
        - openstack-tox-pylint
