- project:
    name: openstack/tobiko
    templates:
      - check-requirements
      - tempest-plugin-jobs
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-pylint
        - openstack-tox-py35
        - openstack-tox-py36
        - openstack-tox-py37
        - openstack-tox-py27
        - tobiko-devstack-neutron-centos
        - tobiko-devstack-neutron
        - tobiko-devstack-neutron-fedora
    gate:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-pylint
        - openstack-tox-py35
        - openstack-tox-py36
        - openstack-tox-py37
        - openstack-tox-py27
