- project:
    name: x/tobiko
    templates:
      - check-requirements
      - tempest-plugin-jobs
      - release-notes-jobs-python3
      - publish-to-pypi
    check:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-pylint
        - openstack-tox-py35
        - openstack-tox-py36
        - openstack-tox-py37
        - openstack-tox-py27
        - openstack-tox-cover
        - tobiko-devstack-neutron-centos-7
        - tobiko-devstack-neutron-centos-7-queens
        - tobiko-devstack-neutron-centos-7-rocky
        - tobiko-devstack-neutron-centos-7-stein
        - tobiko-devstack-neutron-fedora-28
        - tobiko-devstack-neutron-ubuntu-bionic
    gate:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-pylint
        - openstack-tox-py35
        - openstack-tox-py36
        - openstack-tox-py37
        - openstack-tox-py27
