- project:
    templates:
      - build-openstack-docs-pti
      - docs-on-readthedocs
      - openstack-cover-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - openstack-python37-jobs
      - publish-to-pypi
      - build-release-notes-jobs-python3
    vars:
        rtd_webhook_id: '84947'
    check:
      jobs:
        - openstack-tox-pylint
        - tobiko-tox-mypy

        - tobiko-devstack-functional
        - tobiko-devstack-scenario
        - tobiko-devstack-faults-centos-7
        - tobiko-devstack-faults-centos-7-queens
        - tobiko-devstack-faults-ubuntu-bionic

    gate:
      jobs:
        - openstack-tox-pylint
        - tobiko-tox-mypy
