- project:
    name: openstack/tobiko
    templates:
      - check-requirements
      - tempest-plugin-jobs
    check:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-pylint
        - openstack-tox-py35
        - openstack-tox-py36
        - openstack-tox-py27
        - tobiko-devstack-neutron
    gate:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-pylint
        - openstack-tox-py35
        - openstack-tox-py36
        - openstack-tox-py27
        - tobiko-devstack-neutron
